spring.application.name=ms-restaurante
#PATH por default apra toda nuestras apis del msv
spring.datasource.url=jdbc:postgresql://localhost:5433/restaurante_db
spring.datasource.username=root
spring.datasource.password=postgresql220703
spring.jpa.hibernate.ddl-auto=update
spring.sql.show=true
spring.jpa.properties.hibernate.format_sql=true
key.signature=hHRh+AxE3keAHC0UTTg/PdkT1bNzu4/Foa8QGoRDtZgn1eAe1V8J1zLflgOGY9/PVF1Lpmg7jy9ScmECOGZtiA==
storage.local.path= C:/restaurante_uploads/
storage.local.url= http://localhost:8080/uploads/
eureka.client.enabled=false
#logging.level.root=info
#server.port=0
#EUREKA SERVER
#eureka.instance.instance-id=${spring.application.name}:${random.uuid}



